package com.ics.service;

import com.ics.repository.CustomerRepository;
import com.ics.repository.DrinkRepository;
import com.ics.repository.OrderItemRepository;
import com.ics.repository.OrderRepository;
import com.ics.repository.PaymentRepository;
import com.ics.dto.OrderItemDTO;
import com.ics.dto.OrderRequestDTO;
import com.ics.model.*;
import com.ics.model.enums.Branch;
import com.ics.model.enums.OrderStatus;
import com.ics.model.enums.PaymentMethod;
import com.ics.model.enums.PaymentStatus;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class OrderService {

    @Autowired
    private OrderRepository orderRepository;
    @Autowired
    private OrderItemRepository orderItemRepository;
    @Autowired
    private DrinkRepository drinkRepository;
    @Autowired
    private CustomerRepository customerRepository;
    @Autowired
    private PaymentRepository paymentRepository;

    @Transactional
    public Order placeOrder(OrderRequestDTO orderRequestDTO) {
        // 1. Validate and/or Create/Update Customer (if Customer_name/Customer_number are unique)
        Customer customer = customerRepository.findByCustomerNumber(orderRequestDTO.getCustomerPhoneNumber())
                                .orElseGet(() -> {
                                    Customer newCustomer = new Customer();
                                    newCustomer.setCustomerName(orderRequestDTO.getCustomerName());
                                    newCustomer.setCustomerNumber(orderRequestDTO.getCustomerPhoneNumber());
                                    return customerRepository.save(newCustomer);
                                });

        // 2. Create Order
        Order order = new Order();
        // order.setOrderNumber() will be generated by @PrePersist
        order.setBranch(Branch.valueOf(orderRequestDTO.getBranch().toUpperCase())); // Convert string to enum
        order.setCustomerName(orderRequestDTO.getCustomerName());
        order.setCustomerPhoneNumber(orderRequestDTO.getCustomerPhoneNumber());
        order.setOrderStatus(OrderStatus.PENDING); // Initial status
        order.setOrderDate(LocalDateTime.now());
        // Recalculate totalAmount on backend for security
        double calculatedTotal = orderRequestDTO.getOrderItems().stream()
                .mapToDouble(item -> item.getUnit_price() * item.getQuantity())
                .sum();
        if (Math.abs(calculatedTotal - orderRequestDTO.getTotalAmount()) > 0.01) { // Allow for small floating point discrepancies
            throw new IllegalArgumentException("Total amount mismatch. Frontend total: " + orderRequestDTO.getTotalAmount() + ", Backend calculated total: " + calculatedTotal);
        }
        order.setTotalAmount(calculatedTotal);
        // If you add delivery_address and special_instructions to your 'orders' table entity:
        // order.setDeliveryAddress(orderRequestDTO.getDeliveryAddress() + ", " + orderRequestDTO.getDeliveryCity() + (orderRequestDTO.getDeliveryPostalCode() != null ? ", " + orderRequestDTO.getDeliveryPostalCode() : ""));
        // order.setSpecialInstructions(orderRequestDTO.getSpecialInstructions());

        Order savedOrder = orderRepository.save(order);

        // 3. Create Order Items
        List<OrderItem> orderItems = new ArrayList<>();
        for (OrderItemDTO itemDTO : orderRequestDTO.getOrderItems()) {
            Optional<Drink> drinkOptional = drinkRepository.findByDrinkName(itemDTO.getDrink_name());
            if (drinkOptional.isEmpty()) {
                throw new IllegalArgumentException("Drink not found: " + itemDTO.getDrink_name());
            }
            Drink drink = drinkOptional.get();

            // Optional: Check available stock (drink.getDrinkQuantity()) and update it
            // if (drink.getDrinkQuantity() < itemDTO.getQuantity()) {
            //     throw new RuntimeException("Not enough stock for " + itemDTO.getDrink_name());
            // }
            // drink.setDrinkQuantity(drink.getDrinkQuantity() - itemDTO.getQuantity());
            // drinkRepository.save(drink);

            OrderItem orderItem = new OrderItem();
            orderItem.setOrder(savedOrder);
            orderItem.setDrink(drink); // Link to the Drink entity
            orderItem.setQuantity(itemDTO.getQuantity());
            orderItem.setUnitPrice(itemDTO.getUnit_price());
            orderItem.setTotalPrice(itemDTO.getTotal_price());
            orderItems.add(orderItem);
        }
        orderItemRepository.saveAll(orderItems); // Save all order items in a batch

        // Set order items on the order entity (important for relationship management)
        savedOrder.setOrderItems(orderItems);


        // 4. Create Payment
        Payment payment = new Payment();
        payment.setOrder(savedOrder);
        payment.setCustomerNumber(orderRequestDTO.getCustomerPhoneNumber());
        payment.setPaymentMethod(PaymentMethod.valueOf(orderRequestDTO.getPaymentMethod().replace('-', '_').toUpperCase())); // Handle M-Pesa to M_PESA
        payment.setPaymentStatus(PaymentStatus.PENDING); // Initial payment status
        // For M-PESA/CARD: Initiate actual payment gateway call here.
        // For CASH_ON_DELIVERY: Status might immediately be set to SUCCESS or special handling.
        // payment.setTransactionId(generateTransactionId()); // Get this from the payment gateway response

        // For demonstration, setting a dummy transaction ID
        payment.setTransactionId(generateDummyTransactionId(orderRequestDTO.getPaymentMethod()));

        paymentRepository.save(payment);
        savedOrder.setPayment(payment); // Link payment to order

        return savedOrder;
    }

    private String generateDummyTransactionId(String paymentMethod) {
        // In a real app, this would come from the payment gateway
        if ("M-PESA".equals(paymentMethod)) {
            return "MPESA-" + System.currentTimeMillis();
        } else if ("CARD".equals(paymentMethod)) {
            return "CARD-" + System.currentTimeMillis();
        } else {
            return "COD-" + System.currentTimeMillis();
        }
    }
}
